services:
  extension-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-blade-visualizer-dev
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000" # 拡張機能のデバッグ用ポート
    command: tail -f /dev/null # コンテナを起動状態に保つ
    tty: true
    stdin_open: true

volumes:
  node_modules:
